# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - StoreApp
      - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar cloud connection'
    organization: 'jetwash787'
    scannerMode: 'MSBuild'
    projectKey: 'jetwash787_order-app'
    projectName: 'order-app'
    extraProperties: sonar.exclusions=**/lib/**

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
  workingDirectory: StoreApp

- script: dotnet test --no-build --configuration $(buildConfiguration)
  displayName: 'dotnet test'
  workingDirectory: StoreApp

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  displayName: dotnet publish
  workingDirectory: StoreApp

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(f7e52e4c-88e0-4b61-ac00-4e94765c9a23)'
    appType: 'webApp'
    WebAppName: 'liberatore-training-app'
    packageForLinux: 'StoreApp/publish'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'